name: CMake

on:
  push:
    branches: [ "main" ]

env:
  BUILD_TYPE: RelWithDebInfo
  BACKTRACE_SUBMIT_TOKEN: ${{ secrets.BACKTRACE_SUBMIT_TOKEN }}

concurrency:
  group: 'vlink'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ['self-hosted', 'windows']
    if: ${{ !contains(github.event.head_commit.message, 'skip-ci') }}

    steps:
      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: Update vcpkg
        working-directory: C:/vcpkg
        run: git fetch reito reito && git reset --hard reito/reito

      - name: Fetch latest vtslink-client
        working-directory: C:/vtslink/client
        run: git fetch && git reset --hard origin/main && git submodule update

      - name: Fetch latest updator
        working-directory: C:/vtslink/updator
        run: git fetch && git reset --hard origin/master

      - name: Fetch latest updator config
        working-directory: C:/vtslink/config
        run: git fetch && git reset --hard origin/ci

      - name: Remove previous build binary
        working-directory: C:/vtslink/client/out/build
        run: 'if (test-path bin) { remove-item -r bin }'

      - name: Remove previous install binary
        working-directory: C:/vtslink/client/out
        run: 'if (test-path install) { remove-item -r install }'

      - name: Configure CMake
        working-directory: C:/vtslink/client
        run: cmake -G Ninja -B C:/vtslink/client/out/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=C:/vtslink/client/out/install

      - name: Build
        working-directory: C:/vtslink/client
        run: cmake --build C:/vtslink/client/out/build --target VTSLink -j $NUMBER_OF_PROCESSORS

      - name: Install
        working-directory: C:/vtslink/client
        run: cmake --build C:/vtslink/client/out/build --config ${{env.BUILD_TYPE}} --target install -j $NUMBER_OF_PROCESSORS

      - name: Remove previous install binary
        working-directory: C:/vtslink/client/out/install/bin
        run: 'if (test-path vc_redist.x64.exe) { remove-item vc_redist.x64.exe }'

      - name: Build Updator uploader
        working-directory: 'C:/vtslink/updator/Updator.Uploader'
        run: 'dotnet build -o C:/vtslink/uploader'

      - name: Publish build
        shell: pwsh
        run: | 
          dotnet C:/vtslink/uploader/Updator.Uploader.dll `
          --config=C:/vtslink/config/vtslink/config.json `
          --distribution-root=C:/vtslink/client/out/install `
          --update-log="> ${{github.event.head_commit.message}}"

      - name: Upload debug symbol
        shell: pwsh
        run: |
          curl -F "upload_file=@C:/vtslink/client/out/install/pdb/VTSLink.pdb" `
          -X POST `
          "https://submit.backtrace.io/reito/${{secrets.BACKTRACE_SYMBOL_TOKEN}}/symbols"
